# Custom nav
nav:
  title: "Mint Forge"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  GitHub: ""

# Custom footer
mail: kevinjobs@qq.com
copyright: All rights reserved @Kevin JOBS

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  home: ""
  about: /about

auto_excerpt:
  enable: true
  length: 150
  
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false